### ISSUE TITLE
Some web pages can not save content with Capture Page Snapshot.

### ISSUE THREAD

**Issue by ajmz** [coddingtonbear/obsidian-web#10]
Some web pages can not save content with Capture Page Snapshot, such as this issue page (github.com), v1.3.5.

**Comment by coddingtonbear** [comment]
I'm afraid we're leveraging https://github.com/mozilla/readability for identifying and capturing page content, @ajmz -- feel free to post your concerns about particular pages to that project, but unfortunately it's out of this project's hands.

Good luck!
