### ISSUE TITLE
{{filename page.title}} should also strip from "#"

### ISSUE THREAD

**Issue by LightTemplar** [coddingtonbear/obsidian-web#106]
I tried to save this page: https://github.com/coddingtonbear/obsidian-web/discussions/82 and filename was cut after "Discussion ". As I manually removed "#" from filename, it was stored as it should. So, I think, {{filename page.title}} should also strip from "#"

I'm on Kubuntu 22.04.

**Comment by coddingtonbear** [comment]
Yeah, that's probably right; the logic we're using for generating a "filename-safe" name is here: https://github.com/coddingtonbear/obsidian-web/blob/f2ad5b45cc54d6407c10c3298e17c8eb8d97b1a9/src/handlebars.ts#LL32C42-L32C42  feel free to correct it and file a pull request.

**Comment by coddingtonbear** [comment]
A  fix for this was released some time back; maybe in 2.2.4?
