### ISSUE TITLE
Option to remove extraneous page content

### ISSUE THREAD

**Issue by sinewave** [coddingtonbear/obsidian-web#2]
Wow, just stumbled across this extension and it looks amazing!! Really loving the different template abilities and all the  configurability.

One request I'd like to make after comparing the page content that's downloaded to something like [MarkDownload](https://chrome.google.com/webstore/detail/markdownload-markdown-web/pcmpcfapbekmbjjkdalcgopdkipoggdi), which is the extension I've been using, is the difference in the amount of content that's extracted.

Obsidian Web also seems to be capturing a lot of extraneous content such as page navigation links, comments, hidden markup, etc.. 

Perhaps an option to download a stripped down "Readability" version of the page?

Tony

**Comment by coddingtonbear** [comment]
Hey there @sinewave!  I know this isn't something I've made super clear on this particular repo, but could I convince you into starting a discussion under the discussions tab above for feature requests?  For my own sanity, I try to make "Issues" be for only actual bug reports or committed work.

I totally agree that the current markdown page content as it is right now is excessive, though, but might need to convince somebody into filing a PR that improves upon the current functionality.

Cheers!

**Comment by sinewave** [comment]
Ok, created a new discussion! Really hoping someone can tackle this as I’m currently torn between the additional templating options vs having to do a lot of post clipping cleanup.
