### ISSUE TITLE
clipper github issue is error

### ISSUE THREAD

**Issue by seyeeL** [coddingtonbear/obsidian-web#27]
The file will lost '.md'

**Comment by coddingtonbear** [comment]
It's a little difficult to piece together how to help you given that you haven't described what exactly you're doing when you encounter this problem, but I can tell you that this tool does allow you to define how the filename of your "clipped" page is named -- including setting a file extension (e.g. `.md`).  Given that fact, I'm afraid I think you might just have misconfigured your template.

If you were to get a screenshot of the template you're using, I or somebody else could possibly point you in the right direction around what you've overlooked, but in any case, there's very unlikely to be a bug here.  Do feel free to start a discussion (see the "Discussions" tab) if you're still stuck; what I'd recommend doing is titling it something like "Why is my clipped page missing the `.md` extension?" and including a screenshot of the template you're using in your discussion post.  

Cheers & good luck!
