### ISSUE TITLE
why the api key was not accepted by chrome

### ISSUE THREAD

**Issue by glanceofwind** [coddingtonbear/obsidian-web#32]
![image](https://user-images.githubusercontent.com/102296588/186115307-8c382965-531a-4bb4-903f-70d8e610be29.png)
![image](https://user-images.githubusercontent.com/102296588/186115658-9a991ec1-5736-41b4-a78b-67c5b5e83109.png)
![image](https://user-images.githubusercontent.com/102296588/186115667-77c3d4f2-db01-424d-9fc9-7ad6bffe811f.png)
![image](https://user-images.githubusercontent.com/102296588/186115743-5edd6819-9f8e-40cb-8693-6a53d6e68f66.png)

**Comment by woshichuanqilz** [comment]
你这个问题怎么解决的?
