### ISSUE TITLE
Can not access page when page first loaded

### ISSUE THREAD

**Issue by acrobatman** [coddingtonbear/obsidian-web#41]
Hi, I'm using Microsoft Edge browser 105.0.1343.53 x64 and install this extension from chrome web store.
Also, I installed Local Rest API plugin.

But when I open the web page, it can not access page, and can not set it to acces all host.
I only can access web page by click this extension every time.

Here is the snapshot:

![Screenshot 2022-10-01 091747](https://user-images.githubusercontent.com/16357426/193377812-96c287cd-4f64-48b6-b1c3-33f79c5a9806.png)

**Comment by coddingtonbear** [comment]
I'm afraid this extension is only tested and supported for use on Chrome.  If you'd like to see if you can find help from others in the community, though, feel free to open a Discussion on the "Discussions" tab.

Cheers & good luck!
