### ISSUE TITLE
Port to Firefox Extension

### ISSUE THREAD

**Issue by ramisedhom** [coddingtonbear/obsidian-web#5]
Is it in the roadmap to port this nice extension to Firefox?

**Comment by coddingtonbear** [comment]
Hey there @ramisedhom -- for feature requests, please start a discussion under the "Discussions" tab rather than filing an issue.  On this project (like many others), "Issues" is for only bugs and committed work.

To answer your question briefly, though: probably eventually?

**Comment by ramisedhom** [comment]
@coddingtonbear sorry didn't notice that you're using discussions section

**Comment by coddingtonbear** [comment]
Oh, there's no reason to be sorry -- that you didn't know that is entirely my fault.  I just haven't found the time to put together a "New Issue" template that'll make that clear.

**Comment by adityaprasoon** [comment]
There is discussion for this [here](https://github.com/coddingtonbear/obsidian-web/discussions/46#discussion-4476444).
