### ISSUE TITLE
Appends content to the end of the currently opened note 

### ISSUE THREAD

**Issue by Issam-seghir** [coddingtonbear/obsidian-web#64]
I read the [Local REST API for Obsidian Doc](https://coddingtonbear.github.io/obsidian-local-rest-api/#/Active%20File/post_active_)
and I'm trying to create a template to append content to the end of the currently opened note 

this is my template :

![image](https://user-images.githubusercontent.com/74573675/200842891-dfa3b107-516b-40ff-aea9-2b454b71766f.png)

And when I test this template with the selected test I get this error message : 

![image](https://user-images.githubusercontent.com/74573675/200843327-a25a289a-36d4-492a-822c-e848e851907b.png)

What am I doing wrong and how can I modify the template to make it work properly?

**Comment by coddingtonbear** [comment]
That feature exists only in versions greater than 1.5.0 of Local REST API.  It's very likely that you're just not using a new enough version of it  Go into your obsidian community plugin settings, press the button for checking for updates, and install the update for that particular plugin.

**Comment by Issam-seghir** [comment]
> That feature exists only in versions greater than 1.5.0 of Local REST API. It's very likely that you're just not using a new enough version of it. Go into your obsidian community plugin settings, press the button for checking for updates, and install the update for that particular plugin.

I  update the plugin and it works like a charm thank you for this great extension
